### ISSUE TITLE
Many errors since last update

### ISSUE THREAD

**Issue by Gaetanbrl** [geosolutions-it/MapStoreExtension#10]
Hi,

I had update my plugin fork env from this lastest master branch.
But the plugin seems not work anymore.

Now, some of this contexte tools doesn't works to.
http://localhost:8081/#/viewer/openlayers/13184

Are there some many new points to take into account from march ?

As well, i use a custom config.json to use my own contexte.
Layers are loaded but i can't use identify or filters as before. 

Else, branch 2021.01.xx seems to be broken (just clone and start) : 

```
ERROR in ./MapStore2/web/client/components/print/PrintPreview.jsx 35:0-66
Module not found: Error: Can't resolve 'react-pdf/dist/umd/entry.webpack' in 'C:\Users\gaetanbrl\Documents\git\MapStoreExtension\MapStore2\web\client\components\print'
 @ ./MapStore2/web/client/plugins/print/index.js 19:0-67 186:3-19
 @ ./MapStore2/web/client/plugins/Print.jsx 121:31-66 120:6-634:8
 @ ./MapStore2/web/client/product/plugins.js 91:17-55
 @ ./js/app.jsx 58:14-61
```

**Comment by offtherailz** [comment]
Hi, I fixed the branch 2021.01.xx.
Do you still have the same issues?
I tried the map you linked and now it looks working

**Comment by Gaetanbrl** [comment]
Hi,
Thanks @offtherailz . I will try today.

**Comment by Gaetanbrl** [comment]
Hi,

Tested with `master` and `2021.01.xx` branches, this map works better thanks :

http://localhost:8081/#/viewer/openlayers/13184


I will now move my custom plugin to 2021.01.xx branch to finalize the test.

I'll be back with the result @offtherailz before close this issue.

**Comment by Gaetanbrl** [comment]
Thanks @offtherailz all works fine (custom plugin included). I close.
