### ISSUE TITLE
Webpack-cli - Error on start with node 14

### ISSUE THREAD

**Issue by Gaetanbrl** [geosolutions-it/MapStoreExtension#27]
Hi,

 # Versions
 
 Node v14.16.1
 Npm 6.14.12
 
 # issue
Npm start return webpack-cli error :

```
1% setup initialize[webpack-cli] TypeError: cli.isMultipleCompiler is not a function
1 --hot --inline --content-base .`
```

This seems to come from `webpack-cli` and `webpack `packages version in master branch : 

https://github.com/geosolutions-it/MapStoreExtension/blob/8ae58de1a9e9a25c216ac9ab132a7a6f48e5756d/package.json#L112-L114

```
$ webpack --version
webpack: 5.9.0
webpack-cli: 4.9.0       
webpack-dev-server 3.11.0
```

After upgrade webpack-cli all work fine : 

`npm install webpack-cli@4.10.0`

**Comment by landryb** [comment]
Fwiw, was experiencing the same issue with node v12.22.12 when trying `npm start` on https://github.com/georchestra/mapstore2-cadastrapp, changing webpack-cli to 4.10.0 and running `npm install` fixed it.
