### ISSUE TITLE
[Question] - Change default map

### ISSUE THREAD

**Issue by Gaetanbrl** [geosolutions-it/MapStoreExtension#3]
Hi !

I try to change the default map loaded with `npm start` to load a new `myCustomMap.json` file.

Is it possible ?

Thanks.

**Comment by offtherailz** [comment]
the initial map loaded is `config.json` you can edit the file configure it.
You can use [this reference](https://mapstore.readthedocs.io/en/latest/developer-guide/maps-configuration/) for details about how to configure by hand, or use the UI to add layers, and then export the Map, The json format is the same, so you can replace `config.json` with the exported file.
This of course happens only for this local dev env .

**Comment by offtherailz** [comment]
I improved the documentation with PR #3.

**Comment by Gaetanbrl** [comment]
I had replace `config.json` file by a context exported from mapStore (with plugin export). It's easy and fast ! 

Thank you @offtherailz  it's more clear and really better to work with my default mapContext now ! 👍
