### ISSUE TITLE
Align plugin with 2022.x to get responsivePanel

### ISSUE THREAD

**Issue by Gaetanbrl** [geosolutions-it/MapStoreExtension#30]
Hi,
As explain in MS2 migration guide, the new mapStore2 2022.x contain ResponsivePanel to replace DockPanel and DockablePanel.

So, after some test in Mapstore2-GeOrchestra master branch (in Rennes Metropole test env), some plugins don't works anymore because of this panel (i guess).

Now, i need to migrate the plugin to use responsivePanel but MapStoreExtension submodule is not align with last MapStore2 2022.x  and ResponsivePanel missing.

https://github.com/geosolutions-it/MapStore2/tree/fac9d4aa9d5b1c43b559d50820bf6188f81de8f6/web/client/components/misc/panels

Is it possible to align MapStoreExtension to get last submodule version ?

**Comment by tdipisa** [comment]
@Gaetanbrl MapStoreExtensions is currently updated to the last release of MS 2022.01.02. As soon as we create next week the stable branch for the next major release we will also update the revision here accordingly.

**Comment by Gaetanbrl** [comment]
ok thanks, i understand. So, wait next major release integration ;)

**Comment by Gaetanbrl** [comment]
hi @tdipisa !
Some news about this issue ?

**Comment by tdipisa** [comment]
@Gaetanbrl not yet, we have just started the first tests of the new stable MS branch. We will try to give you an update next days.

**Comment by Gaetanbrl** [comment]
ok thanks.
How can we (the community out of the main contributors) help you to upgrade this repo in the futur with others next MS2 release ?
Have you a guide ? A process to follow ?

**Comment by tdipisa** [comment]
Hi @Gaetanbrl, the MS team updated the master branch here to align it to the current the MS master one. After this, also a new stable branch (2022.02.xx) has been created to be aligned with the corresponding MS stable branch 2022.02.xx. We are working to implement some semiautomatic procedures to keep this repo updated: the aim is mainly to keep the MS revision of both master and stable branches aligned with the related MS ones and run tests/checks accordingly (see [#8515](https://github.com/geosolutions-it/MapStore2/issues/8515) and [#8516](https://github.com/geosolutions-it/MapStore2/issues/8516)). 
For other  kind of updates mainly related to the downstream project itself these are manual and are always documented for each release in the [migration guidelines](https://mapstore.readthedocs.io/en/latest/developer-guide/mapstore-migration-guide/).

**Comment by Gaetanbrl** [comment]
thanks @tdipisa and teams for the works.
I will pull changes (+ test) and could now align some code with the last release.

I thing i will come back if all works fine (or not).
