### ISSUE TITLE
npm start doesn't work on fresh install 

### ISSUE THREAD

**Issue by isanchez-c2c** [geosolutions-it/MapStoreExtension#7]
Hi,

with versions : 
 - npm : 6.14.11
 - node : v12.21.0

first npm install output : npm warnings + error in screenshot :
![npm_install_error](https://user-images.githubusercontent.com/78360657/112653580-d9f16000-8e4e-11eb-9f8a-783da69a05dc.png)

second npm install ok (just warnings, the error above is gone)

then npm start fails with :

![mapstore-ext-webpack-cli-outdated](https://user-images.githubusercontent.com/78360657/112652731-03f65280-8e4e-11eb-9d84-f0a448c1d01f.png)

#5  seems to fix it

**Comment by offtherailz** [comment]
Thank you for the contribution. your PR looks to solve the issue :+1:
